server:
  port: 8081

spring:
  application:
    name: mapuescuela-flowable
  datasource:
    url: jdbc:h2:mem:mapuescuela;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console

flowable:
  # Crea/actualiza el esquema de Flowable automaticamente (solo para dev).
  database-schema-update: true
  # Despliega automaticamente todo lo que este en resources/processes
  process-definition-location-prefix: classpath:/processes/
  check-process-definitions: true
  async-executor-activate: true

tomas:
  api:
    url: https://mapuescuelaapi-production.up.railway.app/api
